codici = {
    "Atalanta": 1,
    "Bologna": 2,
    "Cagliari": 21,
    "Empoli": 5,
    "Fiorentina": 6,
    "Frosinone": 7,
    "Genoa": 8,
    "Inter": 9,
    "Juventus": 10,
    "Lazio": 11,
    "Lecce": 119,
    "Milan": 12,
    "Monza": 143,
    "Napoli": 13,
    "Roma": 15,
    "Salernitana": 137,
    "Sampdoria": 16,
    "Sassuolo": 17,
    "Spezia": 129,
    "Torino": 18,
    "Udinese": 19,
    "Venezia": 138,
    "Verona": 20
}

